### ISSUE TITLE
Services running on Tuners?

### ISSUE THREAD

**Issue by holgerlembke** [oe-alliance/e2openplugin-OpenWebif#29]
Hi.

Is there any way to get information about which service is running on each tuner?

With /web/deviceinfo I get the tuners, with /web/getcurrent (I assume) I get the last tuner set.

I have a two tuner solution (dvbt+s) and now stream rtl (dvbs) and view ard (dvbt) on tv. As far as I see, there is no way to get this information via /web/-interface.

Any hints? Thanks!

**Comment by arn354** [comment]
Sorry not having seen this - right now you are right - i was also not able to find code which could provide that information from openWebif.

**Comment by Schimmelreiter** [comment]
It's not easy to get this information from E2 either ... that's probably why it was never implemented in OWIF.
