### ISSUE TITLE
more settings in webif

### ISSUE THREAD

**Issue by N17ro** [oe-alliance/e2openplugin-OpenWebif#33]
Hi , would like first say thanks for this amazing stuff, i love it with my duo2
i see some pics with full settings on openwebif internet page  , i would like to know how to please .
see attach file 
(hope i m at good place for ask, sorry if not)

regards
![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313034303239342f313838393031342f31636361626239382d376131352d313165332d383232372d6139353861383835386637382e6a7067](https://cloud.githubusercontent.com/assets/23095804/19761187/26833008-9c35-11e6-8ded-43c6c706b610.jpg)

**Comment by jbleyel** [comment]
What you mean with "more settings"?
Please tell us what settings you are missing.

**Comment by N17ro** [comment]
Hi   , i have just basic ones , i would like have access to transcoding setup like on the pics :) and more

**Comment by arn354** [comment]
depends what your box supports and which transcodingsetup is used therefore.
openwebif does not make voodoo - it "takes" options from installed plugins.
