### ISSUE TITLE
Openwebif does not recognise place holders

### ISSUE THREAD

**Issue by AbuBaniaz** [oe-alliance/e2openplugin-OpenWebif#41]
At the moment, place holders are not recognised
#SERVICE 1:832:d:0:0:0:0:0:0:0:

Can we add this to the version we build for OE-A.

**Comment by jbleyel** [comment]
No issues here please.

**Comment by AbuBaniaz** [comment]
we build from here.  Requests elsewhere are called "shit"

**Comment by AbuBaniaz** [comment]
If I am not mistaken, someone actually asked fro ABM to stop using place holders.

**Comment by jbleyel** [comment]
The base source is here -> https://github.com/E2OpenPlugins/e2openplugin-OpenWebif
I do not make any changes here.
So please open issues only on the base source.

but anyway.
What is your exact problem with the hidden makers?

**Comment by AbuBaniaz** [comment]
They are not recognised. You just get a long list of blanks instead of being hidden.

**Comment by jbleyel** [comment]
Where exactly?

**Comment by jbleyel** [comment]
I have removed the hidden markers in channel list.

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/fd74b1adec7c7a633717141141ac9192411015b1

I think this is what you want.
Please wait for version 1.1 we need some more tests.

**Comment by Schimmelreiter** [comment]
Did you read what jbleyel said?
The fix is in the 1.1-DEV branch, not yet in master.

**Comment by AbuBaniaz** [comment]
I started typing before he posted.

**Comment by jbleyel** [comment]
As i said .. please wait for the merge of 1.1-DEV to master.
OR get the 1.1 and help us testing of 1.1.
